kind: Service
apiVersion: v1
metadata:
  name:  ai-service
  labels:
    name:  ai-service
spec:
  selector:
    app:  ai-server
  type:  ClusterIP
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  3000